# Generated by Django 5.2.8 on 2025-11-22 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('image_resultat', models.ImageField(blank=True, null=True, upload_to='resultats/')),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('nombre_poubelles', models.IntegerField(default=0)),
                ('nombre_vides', models.IntegerField(default=0)),
                ('nombre_pleines', models.IntegerField(default=0)),
                ('detections_json', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date_upload'],
            },
        ),
    ]
